Repository 2024-Techeer-Summer-Bootcamp-Team-D/MVStudio-Backend, pull requests merged in 2024-07, with the labels that each got.

#15 [feat] 회원 정보 조회 기능 구현
  member/views.py
Labels: 🚀 Feat

#16 [feat] 로그인 기능 구현
  member/serializers.py
  member/urls.py
  member/views.py
  mv_creator/views.py
Labels: 🚀 Feat

#18 [chore] Amazon RDS 연결
  config/settings.py
  docker-compose-dev.yml
  member/views.py
  requirements.txt
Labels: 🧭 Chore

#22 [feat] : 회원 정보 수정 관련 API 기능 구현
  config/settings.py
  docker-compose-dev.yml
  docker-compose.yml
  member/migrations/0001_initial.py
  member/models.py
  member/serializers.py
  member/views.py
  requirements.txt
Labels: 🚀 Feat

#23 [feat] 가사 생성 기능 API 구현
  config/settings.py
  config/urls.py
  docker-compose-dev.yml
  member/serializers.py
  member/urls.py
  music_videos/__init__.py
  music_videos/admin.py
  music_videos/apps.py
  music_videos/migrations/0001_initial.py
  music_videos/migrations/__init__.py
  music_videos/models.py
  music_videos/serializers.py
  music_videos/tests.py
  music_videos/urls.py
  music_videos/views.py
  mv_creator/apps.py
  mv_creator/models.py
  mv_creator/urls.py
  mv_creator/views.py
  requirements.txt
Labels: 🚀 Feat

#25 [Feat] 데이터베이스 물리적 설계 및 기타 코드 수정
  member/migrations/0001_initial.py
  member/models.py
  music_videos/migrations/0001_initial.py
  music_videos/models.py
  music_videos/serializers.py
  music_videos/urls.py
  music_videos/views.py
  requirements.txt
Labels: 🚀 Feat

#28 [feat] 국가 리스트 조회 기능 구현
  member/models.py
  member/serializers.py
  member/urls.py
  member/views.py
Labels: 🚀 Feat

#30 [feat] 장르, 악기 리스트 조회 기능 구현
  member/urls.py
  member/views.py
  music_videos/urls.py
  music_videos/views.py
Labels: 🚀 Feat

#31 [feat] 뮤직비디오 생성 기능 구현
  config/settings.py
  music_videos/models.py
  music_videos/serializers.py
  music_videos/views.py
  requirements.txt
Labels: 🚀 Feat

#34 [feat] 뮤직비디오 삭제 기능 구현 완료
  music_videos/models.py
  music_videos/serializers.py
  music_videos/urls.py
  music_videos/views.py
Labels: 🚀 Feat

#38 [feat] 뮤직비디오 나라별 조회 기능 구현
  .gitignore
  docker-compose-dev.yml
  docker-compose.yml
  member/migrations/0001_initial.py
  member/migrations/__init__.py
  music_videos/migrations/0001_initial.py
  music_videos/migrations/__init__.py
  music_videos/views.py
Labels: 🚀 Feat

#40 [feat] 뮤직비디오 시청 기록 기능 구현
  Dockerfile
  music_videos/models.py
  music_videos/serializers.py
  music_videos/urls.py
  music_videos/views.py
  requirements.txt
Labels: 🚀 Feat

#43 [feat] 뮤직비디오 시청 기록 조회 기능 구현
  Dockerfile
  config/__init__.py
  config/celery.py
  config/settings.py
  docker-compose-dev.yml
  music_videos/__init__.py
  music_videos/serializers.py
  music_videos/tasks.py
  music_videos/views.py
  requirements.txt
Labels: 🚀 Feat

#44 [feat] 뮤직비디오 시청 기록 조회 기능 구현
  music_videos/urls.py
  music_videos/views.py
Labels: 🚀 Feat

#46 [feat] 유튜브 채널 URL 반환 기능 구현
  config/settings.py
  config/urls.py
  oauth/admin.py
  oauth/apps.py
  oauth/models.py
  oauth/tests.py
  oauth/urls.py
  oauth/views.py
  requirements.txt
Labels: 🚀 Feat

#48 [feat] S3 수정
  config/settings.py
  member/views.py
  music_videos/s3_utils.py
  music_videos/views.py
Labels: 🚀 Feat

#49 [chore] 도커 개발 환경 세팅
  docker-compose-dev.yml
  docker-compose.yml
Labels: 🧭 Chore

#51 [feat] Elastic Search 검색 엔진 구현
  config/celery.py
  config/settings.py
  music_videos/documents.py
  music_videos/tasks.py
  music_videos/urls.py
  music_videos/views.py
  requirements.txt
Labels: 🚀 Feat

#53 [fix] django cors error 해결
  config/settings.py
  requirements.txt
Labels: 🏷 Fix

#56 [feat] RabbitMQ + Celery 비동기 구현
  config/__init__.py
  music_videos/tasks.py
  music_videos/views.py
Labels: 🚀 Feat

#57 [feat] 로그인 및 회원가입 API Response Body id값 추가
  member/serializers.py
  member/views.py
Labels: 🚀 Feat

#59 [feat] api 상태 코드 수정
  config/urls.py
  member/urls.py
  member/views.py
  music_videos/urls.py
  music_videos/views.py
  oauth/urls.py
Labels: 🚀 Feat

#63 [feat] 각종 API 수정
  config/settings.py
  config/urls.py
  member/views.py
  music_videos/models.py
  music_videos/serializers.py
  music_videos/urls.py
  music_videos/views.py
  oauth/urls.py
  oauth/views.py
Labels: 🚀 Feat

#64 [feat] 뮤직비디오 생성 기능 개선
  config/celery.py
  config/settings.py
  music_videos/tasks.py
  music_videos/urls.py
  music_videos/views.py
Labels: 🚀 Feat

#68 [feat] 뮤직비디오 제작 기능 수정
  music_videos/tasks.py
  music_videos/urls.py
  music_videos/views.py
Labels: 🚀 Feat

#70 [feat] RunwayML model 수정
  music_videos/tasks.py
  music_videos/views.py
Labels: 🚀 Feat

#72 [feat] 가사 생성 프롬프팅 수정
  music_videos/views.py
Labels: 🚀 Feat

#75 [feat] API 수정사항 수정
  config/urls.py
  member/urls.py
  music_videos/serializers.py
  music_videos/urls.py
  music_videos/views.py
  oauth/urls.py
Labels: 🚀 Feat

#76 [feat] JWT 토큰 방식 로그인 구현
  config/settings.py
  member/models.py
  member/serializers.py
  member/urls.py
  member/views.py
  music_videos/models.py
  music_videos/serializers.py
  music_videos/tasks.py
  music_videos/urls.py
  music_videos/views.py
  oauth/authenticate.py
  oauth/mixins.py
  oauth/services.py
  oauth/urls.py
  oauth/utils.py
  oauth/views.py
  requirements.txt
Labels: 🚀 Feat

#78 [fix] url 엔드포인트 수정 및 password 재확인 로직 삭제
  member/serializers.py
  member/urls.py
  oauth/urls.py
Labels: 🏷 Fix

#80 [feat] 비회원 권한 수정
  member/views.py
  music_videos/urls.py
  music_videos/views.py
  oauth/mixins.py
  oauth/views.py
Labels: 🚀 Feat

#82 [feat] 구글 소셜 로그인 redirect url 수정
  config/settings.py
  oauth/views.py
Labels: 🚀 Feat

#84 [feat] 채널 분석 조회 기능 구현
  member/models.py
  member/serializers.py
  member/urls.py
  member/views.py
  music_videos/models.py
  music_videos/serializers.py
  music_videos/urls.py
  music_videos/views.py
Labels: 🚀 Feat

#86 [feat] 시청 기록 등록 기능 수정
  member/views.py
  music_videos/views.py
Labels: 🚀 Feat

#88 [feat] 차트 앱 추가 후 수정
  charts/__init__.py
  charts/admin.py
  charts/apps.py
  charts/models.py
  charts/tests.py
  charts/urls.py
  charts/views.py
  config/settings.py
  config/urls.py
  member/urls.py
  member/views.py
Labels: 🚀 Feat

#90 [feat] 가사 생성 응답값 형식 수정
  music_videos/views.py
Labels: 🚀 Feat

#94 [feat] 카카오페이 결제 API 구현
  config/settings.py
  member/callback.py
  member/constants.py
  member/models.py
  member/payment.py
  member/serializers.py
  member/urls.py
  member/views.py
  oauth/apis.py
  oauth/utils.py
  oauth/views.py
Labels: 🚀 Feat

#95 [feat] API swagger 수정
  member/models.py
  member/views.py
  music_videos/models.py
  music_videos/urls.py
  music_videos/views.py
Labels: 🚀 Feat

#100 [feat] api 수정 완료
  member/views.py
Labels: 🚀 Feat

#102 [feat] 음악 스타일 프롬프팅 수정
  music_videos/tasks.py
Labels: 🚀 Feat

#105 [feat] 가사 프롬프팅 수정
  music_videos/views.py
Labels: 🚀 Feat

#106 [feat] RabbitMQ Exchange 설정
  config/celery.py
  config/settings.py
  music_videos/models.py
  music_videos/serializers.py
  music_videos/tasks.py
  music_videos/views.py
  oauth/utils.py
  oauth/views.py
Labels: 🚀 Feat

#107 [feat] 뮤직비디오 목록 조회 수정
  music_videos/views.py
Labels: 🚀 Feat

#109 [feat] 멤버 credits 조회 기능 구현
  member/urls.py
  member/views.py
  music_videos/views.py
Labels: 🚀 Feat

#112 [refactor] music video logging 및 response_data 리팩토링
  music_videos/serializers.py
  music_videos/views.py
  oauth/authenticate.py
Labels: 🧹 Refactor

#113 [feat] member 앱 리팩토링 완료
  member/serializers.py
  member/views.py
Labels: 🧹 Refactor

#115 [feat] youtube 동영상 업로드 기능 구현
  charts/views.py
  oauth/services.py
  oauth/urls.py
  oauth/views.py
Labels: 🚀 Feat

#117 [feat] 유튜브 채널 url 반환 기능 구현
  oauth/urls.py
  oauth/views.py
Labels: 🚀 Feat

#119 [feat] api 및 로깅 방식 통일
  charts/views.py
  member/views.py
  music_videos/serializers.py
Labels: 🚀 Feat

#121 [feat] 뮤직비디오 목록 조회 수정
  music_videos/views.py
Labels: 🚀 Feat

#123 [chore] prometheus 세팅
  config/settings.py
  config/urls.py
  requirements.txt
Labels: 🧭 Chore

#125 [feat] 뮤직비디오 정렬 조회 수정
  music_videos/views.py
Labels: 🚀 Feat

#127 [feat] 예외처리 수정
  member/views.py
  music_videos/views.py
Labels: 🚀 Feat

#130 [feat] 로깅 방식 통일
  charts/views.py
  member/views.py
  music_videos/views.py
Labels: 🚀 Feat

#131 [chore] Logging 세팅
  charts/views.py
  config/settings.py
  member/views.py
  music_videos/views.py
Labels: 🧭 Chore

#133 [feat] 뮤직비디오 생성 시 크레딧 검사 및 차단 구현
  member/models.py
  music_videos/tasks.py
  music_videos/views.py
Labels: 🚀 Feat

#135 [feat] 뮤직비디오 크레딧 차감 시점 변경
  music_videos/tasks.py
  music_videos/views.py
Labels: 🚀 Feat

#141 [feat] KakaoPay Callback url 수정
  config/settings.py
  member/payment.py
Labels: 🚀 Feat

#143 [feat] 커버 이미지 조회 기능 구현
  music_videos/serializers.py
  music_videos/urls.py
  music_videos/views.py
Labels: 🚀 Feat

#145 [feat] API 수정
  charts/views.py
  music_videos/views.py
Labels: 🚀 Feat

#146 [feat] 뮤직비디오 유튜브 업로드 기능 수정
  config/settings.py
  member/views.py
  oauth/authenticate.py
  oauth/handler.py
  oauth/services.py
  oauth/urls.py
  oauth/views.py
Labels: 🚀 Feat

#149 [feat] 뮤직비디오 조회 기능 username 추가
  music_videos/serializers.py
Labels: 🚀 Feat

#151 [feat] 커버 이미지 페이지네이션 수정
  music_videos/views.py
Labels: 🚀 Feat
